---

apt_repos:
  - ppa:ansible/ansible
  - ppa:ondrej/apache2

apt_packages:
  - imagemagick
  - libmagickcore-dev
  - libmagickwand-dev
  - libmysqlclient-dev
  - htop
  - vim
  - time
  - tree
  - make
  - apparmor-utils
  - python-software-properties
  - python-dev
  - python-setuptools
  - python
  - python-simplejson
  - python-passlib
  - software-properties-common
  - rsync
  - libssl-dev
  - zlib1g-dev
  - rng-tools
  - cgroup-bin
  - git

pip_packages:
  - setuptools
  - paramiko
  - pyyaml
  - jinja2
  - markupsafe
  - MySQL-python
  - ansible==1.9.4
