---
- name: Create folders for Jenkins jobs
  file:
    path: /var/lib/jenkins/jobs/{{ item.name }}
    state: directory
    owner: jenkins
    group: jenkins
  with_items: jenkins_jobs

- name: Copy Jenkins jobs
  template:
    src: jobs/{{ item.template }}
    dest: /var/lib/jenkins/jobs/{{ item.name }}/config.xml
    owner: jenkins
    group: jenkins
    force: yes
  notify: Restart Jenkins
  with_items: jenkins_jobs

# Automatically scan users directory.
- name: Create folders for users
  file:
    path: /var/lib/jenkins/users/{{ item | basename | regex_replace('\.xml.j2','') }}
    state: directory
    owner: jenkins
    group: jenkins
  with_fileglob:
    - ../templates/users/*.j2

- name: Copy user configs
  template:
    src: users/{{ item | basename }}
    dest: /var/lib/jenkins/users/{{ item | basename | regex_replace('\.xml.j2','') }}/config.xml
    owner: jenkins
    group: jenkins
    mode: 0755
    force: yes
  notify: Restart Jenkins
  with_fileglob:
    - ../templates/users/*.j2

# Automatically scan configs directory.
- name: Copy Jenkins configs
  template:
    src: configs/{{ item | basename }}
    dest: /var/lib/jenkins/{{ item | basename | regex_replace('\.xml','') }}
    owner: jenkins
    group: jenkins
    force: yes
  notify: Restart Jenkins
  with_fileglob:
    - ../templates/configs/*.j2
