---
# This playbook should be executed using 
# ansible-playbook jenkinsbox.yml
# command
# Developed for ansible version >= 1.7
- hosts: CHANGE_ME
  gather_facts: yes
  remote_user: root

  vars:
    project_name: CHANGE_ME

    # Drush for Drupal 7.
    drush_composer_version: 6.*
    # Drush for Drupal 8.
    # drush_composer_version: 8.*

    drushrc:
      drush_usage_log: 1
      drush_usage_send: 1

    # PHP configs.
    cibox_ssl_enable_host: true
    php_apc_enabled_in_ini: true

    # Apache config.
    cibox_ssl_folder: /etc/apache/ssl
    apache_create_vhosts: true
    apache_vhosts_filename: "vhosts.conf"
    apache_remove_default_vhost: true
    apache_vhosts:
      - {
        servername: "*",
        documentroot: "/var/www"
      }
    apache_vhosts_ssl:
      - {
        servername: "*",
        documentroot: "/var/www",
        certificate_file: "{{ cibox_ssl_folder }}/apache.crt",
        certificate_key_file: "{{ cibox_ssl_folder }}/apache.key",
      }
    apache_mods_enabled:
      - rewrite.load
      - ssl.load

  # @todo cleanup old tags.
  roles:
    - { role: cibox-env }
    - { role: cibox-swap, tags: ["cibox-swap"], when: ansible_virtualization_type != "openvz" }
    - { role: ansible-role-apache }
    - { role: ansible-role-php, tags: ["php-stack"] }
    - { role: ansible-composer, tags: ["ansible-composer", "php-stack"] }
    - { role: cibox-drush, tags: ["php-stack"] }
    - { role: ansible-php-pear, tags: ["ansible-php-pear", "php-stack"] }
    - { role: ansible-role-php-xhprof, tags: ["ansible-php-xhprof", "php-stack"] }
    - { role: ansible-role-mysql, tags: ["mysql", "php-stack", "ansible-role-mysql"] }
    - { role: cibox-jenkins, tags: ["cibox-jenkins"] }
    - { role: cibox-jetty-solr, tags: ["cibox-jetty-solr"] }
    - { role: cibox-sniffers, tags: ["cibox-sniffers", "php-stack"] }
    - { role: cibox-mysql-config, tags: ["mysql", "php-stack", "cibox-mysql-config"] }
    - { role: cibox-ssl-config, tags: ["apache", "php-stack", "ssl", "cibox-ssl-config"] }
    - { role: cibox-behat-selenium2, tags: ["cibox-behat-selenium", "behat-selenium"] }
    - { role: cibox-security }
