---
# This playbook should be executed using 
# ansible-playbook jenkinsbox.yml
# command
# Developed for ansible version >= 1.7
- hosts: CHANGE_ME
  gather_facts: yes
  remote_user: root

  vars:
    project_name: CHANGE_ME

    apache2_modules:
      - rewrite

    # Drush for Drupal 7.
    drush_composer_version: 6.*
    # Drush for Drupal 8.
    # drush_composer_version: 8.*

    drushrc:
      drush_usage_log: 1
      drush_usage_send: 1

    # PHP configs.
    cibox_ssl_enable_host: true
    php_apc_enabled_in_ini: true

  # @todo cleanup old tags.
  roles:
    - { role: cibox-env }
    - { role: cibox-swap, tags: ["cibox-swap"], when: ansible_virtualization_type != "openvz" }
    - { role: ansible-role-php, tags: ["php-stack"] }
    - { role: ansible-composer, tags: ["ansible-composer", "php-stack"] }
    - { role: cibox-drush, tags: ["php-stack"] }
    - { role: ansible-php-pear, tags: ["ansible-php-pear", "php-stack"] }
    - { role: ansible-role-php-xhprof, tags: ["ansible-php-xhprof", "php-stack"] }
    - { role: ansible-role-mysql, tags: ["mysql", "php-stack", "ansible-role-mysql"] }
    - { role: cibox-jenkins, tags: ["cibox-jenkins"] }
    - { role: cibox-jetty-solr, tags: ["cibox-jetty-solr"] }
    - { role: cibox-sniffers, tags: ["cibox-sniffers", "php-stack"] }
    - { role: cibox-mysql-config, tags: ["mysql", "php-stack", "cibox-mysql-config"] }
    - { role: cibox-ssl-config, tags: ["apache", "php-stack", "ssl", "cibox-ssl-config"] }
    - { role: cibox-behat-selenium2, tags: ["cibox-behat-selenium", "behat-selenium"] }
    - { role: cibox-security }

  tasks:
  # @tag apache role.
  - name: Apache2 modules
    apache2_module: state=present name={{ item }}
    with_items: apache2_modules
    tags:
      - apache
      - php-stack
    notify: Restart apache

  # @tag apache role.
  - name: Copy apache vhost file
    synchronize: src=files/sites-enabled/000-default.conf dest=/etc/apache2/sites-enabled/000-default.conf
    sudo: yes
    tags:
      - apache
      - php-stack
    notify: Restart apache

  # @todo should be removed.
  handlers:
  - name: Restart apache
    service: name=apache2 state=restarted
    tags:
      - mysql
      - apache
      - php-stack
